// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mplaykyjqiklddrufgjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wbGF5a3lqcWlrbGRkcnVmZ2p3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDA3NDQsImV4cCI6MjA2NjUxNjc0NH0.brZKrqqc9z-fDx1z_OEbXmk17zOkX6BD9eh7bN87JVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);